lang_alt =
{
 "eng": "english",
 "ind": "indonesian",
 "jav": "javanese",
 "min": "minangkabau",
 "sun": "sundanese",
 "ban": "balinese",
 "nij": "ngaju",
 "ace": "acehnese",
 "bjn": "banjarese",
 "bbc": "batak toba",
 "bug": "buginese",
 "mad": "madurese",
 "abl": "lampung nyo",
 "jav-bms": "javanese, banyumasan dialect",
 "msa": "malay",
 "tpi": "tok pisin",
 "hmo": "hiri motu",
 "tdt": "tetun dili",
}