lang_alt =
{
 "eng": "english",
 "ind": "indonesian",
 "jav": "javanese",
 "min": "minangkabau",
 "sun": "sundanese",
 "ban": "balinese",
 "nij": "ngaju",
 "ace": "acehnese",
 "bjn": "banjarese",
 "bbc": "batak toba",
 "bug": "buginese",
 "mad": "madurese",
 "abl": "lampung nyo",
 "jav-bms": "javanese, banyumasan dialect",
 "msa": "malay",
 "tpi": "tok pisin",
 "hmo": "hiri motu",
 "tdt": "tetun dili",
 "kaw": "kawi",
 "ara": "arabic",
 "spa": "spanish",
 "jpn": "japanese",
 "kor": "korean",
 "fra": "french",
 "btx": "batak karo",
 "dyk": "dayak",
 "hin": "hindi",
 "rus": "russian",
 "por": "portugese",
 "tha": "thai",
 "vie": "vietnamese",
 "zho": "chinese"
}
